from .modeling_wfvae2 import WFVAE2Model
from .modeling_wfvae_temporal_compressed_v3 import WFVAETemporalCompressedModelV3
from .modeling_wfvae_temporal_compressed_topk import WFVAETemporalCompressedModelTopK
from .WVAE_Compressed_TopK_multi_wavelet import WVAE_Compressed_TopK_multi_wavelet
from .WVAE_Compressed_TopK_multi_wavelet_multi_keep_ratio import WVAE_Compressed_TopK_multi_wavelet_multi_keep_ratio

from .Wan_2_1 import Wan2_1_VAE_Trainable
from .Wan_2_1_multi_wavelet import Wan2_1_VAE_MultiWavelet
from .Wan_2_1_no_cache import Wan2_1_VAE_no_cache
